baseURL = ''
languageCode = 'en-us'
title = 'Stacy Gaudreau'
assetDir = '../src'
staticDir = '../static'
disableKinds = ['skill']

[markup]
  [markup.tableOfContents]
    startlevel = 2
    endLevel = 4
  [markup.highlight]
    noClasses=false
