baseURL = ''
languageCode = 'en-us'
title = 'Software and DevOps Developer'
assetDir = '../src'
staticDir = '../static'
disableKinds = ['skill']

[markup]
  [markup.tableOfContents]
    startlevel = 2
    endLevel = 4
  [markup.highlight]
    noClasses=false

[params]
  cvDownloadUrl = '/CV-StacyGaudreau.pdf'
  linkedinUrl = 'https://www.linkedin.com/in/stacy-gaudreau'
  contactEmail = 'contact@stacygaudreau.com'